// <auto-generated />
namespace Warehouse.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BannerSliderDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BannerSliderDetails));

        string IMigrationMetadata.Id
        {
            get { return "201509221814462_Banner Slider Details"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
